<?php

return[
    'create'   => 'Create',
    'update'   => 'Update',
    'delete'   => 'Delete',
    'permission_name' => 'Permission Name',
    'cancel'   => 'Cancel',
    'update'   => 'Update',
    'permissions' => 'Permissions',
    'role_name'   => 'Role Name',
    'roles'       => 'Roles',
    'name'        => 'Name',
    'email'       => 'Email',
    'password'    => 'Password',
    'select_role' => 'Select Role',
    'address'     => 'Address',
    'phone'       => 'Phone',
    'role'        => 'Role',
    'users'       => 'Users',
    'edit'        => 'Edit',
    'view'        => 'View',
    'status'      => 'Status',
    'active'      => 'Active',
    'inactive'    => 'Inactive',
    'select_status' => 'Select Status',
    'id'            => 'Id',
    'back'          => 'Back',
    'user'          => 'User',
    'role'          => 'Role',
    'created_at'     => 'Created At',
    'updated_at'    => 'Updated At',
    'permission_name' => 'Permission Name',
    'permission'      => 'Permission',
    'user_list'       => 'User list',
    
];